language: go
go:
  - 1.13.x

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kubectl
  - sudo chmod +x /usr/bin/kubectl

install:
  - go get -u golang.org/x/lint/golint
  - go mod download

script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint . | tee /dev/stderr)"
  - go vet -v ./...
  - go test -v ./...
  - CGO_ENABLED=0 go build -o ./kubectx ./cmd/kubectx
  - bats test/kubectx.bats
  - CGO_ENABLED=0 go build -o ./kubens ./cmd/kubens
  - bats test/kubens.bats
